version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-lf
    restart: unless-stopped
    environment:
      POSTGRES_USER: lightfish
      POSTGRES_PASSWORD: "Lf_2026Strong@Pass_lightfish"
      POSTGRES_DB: lf_db
    ports:
      - "54329:5432"  # 👈 高位端口，黑客扫不到
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shared-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:

networks:
  shared-network:
    external: true
    name: shared-network